name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    # container: docker://dvcorg/cml:0-dvc2-base1-gpu
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '12'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc run -n data_load \
            -d src/pipelines/data_load.py \
            -o data/raw/iris.csv \
            -p base,data_load \
            python src/pipelines/data_load.py \
                --config=params.yaml

          pip install -r requirements.txt
          python src/pipelines/evaluate.py --config=params.yaml
          
          cat reports/metrics.json > report.md
          cml-publish reports/confusion_matrix.png --md >> report.md
          cml-publish pr_curve.png --md >> report.md
          cml-send-comment report.md
